# Generated by Django 4.2.6 on 2023-10-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0002_remove_menuitem_named_url_menuitem_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
    ]
